### ISSUE TITLE
Key events do not work from Hosts that intercept them (Ardour for instance)

### ISSUE THREAD

**Issue by WeirdConstructor** [WeirdConstructor/Kickmess#2]
Keyboard events are passed through by hosts like Carla, but Ardour intercepts
key presses/releases. Kickmess needs to handle key_up/key_down coming from
the VST API (see Editor in vst-rs).

**Comment by sjaehn** [comment]
Did you enable keyboard events to be passed to the plugin? In Ardour it's in the header line of the plugin window on the very right side.

**Comment by WeirdConstructor** [comment]
> Did you enable keyboard events to be passed to the plugin? In Ardour it's in the header line of the plugin window on the very right side.

Yes, I've seen that keyboard. I also looked at the source, the key events are forwarded from Gtk to the VST plugin. But my VST API does not handle the key events coming in via VST, only the key events received directly from X11. This is just a reminder for myself :-)

**Comment by WeirdConstructor** [comment]
Fixed in 0.2.2
