### ISSUE TITLE
Crashes when opened in MusE Sequencer

### ISSUE THREAD

**Issue by aliceh75** [WeirdConstructor/Kickmess#9]
Hello,

MusE Sequencer (https://github.com/muse-sequencer/muse) crashes when I try to open this plugin.

Using MusE Sequencer 4.0 (AppImage), and Kickmess main branch, as of today (build locally).

I don't know if the issue is with this plugin or with MusE - thought I 'd start by reporting it here. Let me know if I can get anymore information that would help.

**Comment by WeirdConstructor** [comment]
Hi!

Does it work in other VST hosts for you? Ardour, Carla or Renoise?

**Comment by aliceh75** [comment]
Good question - I'll give it a go and let you know next time I have some music making time 😄

**Comment by aliceh75** [comment]
@luzpaz Thanks for the reminder !

I haven't been using MusE Sequencer for a while, so I don't know if it's still an issue.

It's not an issue for _me_ anymore. As it's been two years, no-one else reported the same issue and Muse Sequencer is now at 4.2.1, I'll close the issue.

There is no useful information on this ticket, so if someone else encounters this they can open a new one.

Thanks !
